### ISSUE TITLE
[2장] 객체의 생성과 파괴

### ISSUE THREAD

**Issue by taehyunnn** [wms-study/book-effective-java#1]

**Comment by taehyunnn** [comment]
1. 책에서 객체를 생성하는 방법으로 생성자, 스태틱 팩토리 생성자, 빌더가 소개되었는데, 그룹에서 컨벤션을 정한다면 어떻게 정할 수 있을까요?
2. 객체 생성의 cost가 비싸다는 것을 어떻게 알 수 있을까요?
3. Long에 Long을 더하는 것과 long에 long을 더하는 것의 차이는 무엇인가요?
4. DB의 객체 생성이 비싸다는 나왔는데 구체적으로 '무엇 때문에', '왜' 비싼가요?
5. 메모리 누수의 원인으로 [자기 메모리를 직접 관리하는 클래스, 캐시, 리스너와 콜백] 이 소개되었는데, 우리 테크타카에서 점검해봐야할 부분이 있을까요?

**Comment by lewisseo91** [comment]
1. 빌더 패턴에 4개 이상이 되어야 값어치를 하지만 시간이 지날 수록 많아지는 경향이 있고, 전환 전에 만들어둔 생성자와 정적 팩터리가 아주 도드라져 보일 것이다 라는 문구가 있었습니다. 
최근에 저희 프로젝트의 메서드도 보면서 같은 생각을 한 적이 있는데 다른 분들은 어떻게 생각하시는 지 궁금한데 질문보다는 나중에 같이 얘기해 봤으면 좋겠어요. 
저는 이 부분을 읽고 먼가 빌더를 통일하는게 좋겠다고 개인적으로 생각했었습니다.

**Comment by zeroest** [comment]
@taehyunnn 
1. 상황에 따라 생성자, 스태틱 팩토리 메서드, 빌더 사용방법이 다를것 같아 컨벤션으로 정의하기 어려울것 같습니다.
2. 루이스님이 참조해주신 유튜브 참조
- https://www.youtube.com/watch?v=ZfW7FwuBd90
3-1. wrapper 클래스들의 연산비용이 실제 업무에서 크게 영향을 줄것 같지 않다고 생각합니다. 
3-2. primative, wrapper 사용에 생각이 다른것 같습니다.
- Tony: primitive가 기본이 되어야 하고 필요에 따라 wrapper를 사용해야한다
  - NPE를 방지할 수 있고 default 값이 설정되어 따로 기본값을 설정할 필요가 없다.
- Zero, Lewis: wrapper 타입 사용이 유연한 상황에 필요할것 같다 
  - Jackson 라이브러리 setter 시점에서 primitive 타입에 null을 세팅하는 문제가 발생할 수 있다.
  - DB 컬럼에 null 허용시 primitive 타입에 대한 대응이 어려울것 같다.
4. 커넥션 풀 사용 이유
- 서버의 한정적 자원 효율적 사용
- 커넥션마다 TCP 핸드셰이크의 비효율성 제거
- https://programmer93.tistory.com/74
- https://1-7171771.tistory.com/119
5. 일급 컬렉션, 캐시 내부 컬렉션 객체에 점검이 필요하다고 생각듭니다.

@lewisseo91 
1. 빌더 패턴으로 통일 하기보다 상황에따라 스태틱 팩토리 메서드, 생성자 등 효율적인 선택이 더 좋을것 같습니다.

**Comment by zeroest** [comment]
@lewisseo91 루이스님이 정리해주신 참조 링크

불필요한 객체 생성 피하기
https://github.com/java-squid/effective-java/issues/6
유한 상태 머신
https://www.youtube.com/watch?v=ZfW7FwuBd90
https://idea-sketch.tistory.com/23
https://github.com/java-squid/effective-java/issues/6
Wrapper class
https://jusungpark.tistory.com/17
https://www.tutorialspoint.com/why-do-we-need-a-wrapper-class-in-java#:~:text=Wrapper%20Class%20will%20convert%20primitive,help%20in%20this%20case%20also.
db 비용
https://p829911.tistory.com/13
https://stackoverflow.com/questions/34303678/database-connection-expensive-to-create#:~:text=Database%20connections%20are%20much%20more,a%20shared%20memory%20pool%2C%20etc.
java memory leak
https://stackoverflow.com/questions/6183415/classes-managing-own-memory
https://medium.com/illegalarguments/debugging-spring-boot-applications-for-memory-leaks-4ba5f8bee75a
https://techblog.woowahan.com/2628/
